name: GitHub Actions 
on: [push]
jobs:
  run_on_Linux:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - run: |
               cmake -H. -B_build
               cmake --build _build
               
        - name: Configure and Build Project
          uses: threal/cmake-action@1.3.0
          
